import assert from 'node:assert/strict';
import { test } from 'node:test';
import { acousticTiming, validSpeechActivity } from '../src/generation/core/alignment-acoustic.ts';
import { applyAcousticTiming } from '../src/reader/audio-acoustic.ts';
import type { AlignmentRuntimeResult } from '../src/generation/core/alignment-adapter.ts';
import type { AlignmentUnitResult, AcousticTimingEstimate } from '../src/generation/contracts.ts';
import type { PlayablePhraseCue } from '../src/reader/audio-clock.ts';
const unit = (index: number): AlignmentUnitResult => ({ unitId: `u${index}`, blockId: 'b', start: index, end: index + 1, spokenRanges: [{start:index,end:index+1}], normalizedRanges: [{start:index,end:index+1}], status: index===1?'low-confidence':'aligned',score:index===1?.2:.98 });
function runtime(): AlignmentRuntimeResult { return {schemaVersion:1,alignerVersion:'pinned',normalizeVersion:'ctc-ja-nfkc-v1',offsetUnit:'utf16',normalizedText:'私が読む',durationSeconds:3,segments:[.98,.2,.98,.98].map((confidence,index)=>({start:index,end:index+1,startSeconds:index<2?.25+index*.2:1.65+(index-2)*.4,endSeconds:index<2?.27+index*.2:1.67+(index-2)*.4,confidence,status:confidence>=.75?'aligned':'low-confidence'})),speechActivity:{version:'pcm-rms-v1',frameSeconds:.01,thresholdRms:.003,intervals:[{startSeconds:.2,endSeconds:.8},{startSeconds:1.6,endSeconds:2.4}]}}; }
function cue(index: number, start: number, end: number, reliable=false): PlayablePhraseCue { const value={id:`u${index}`,blockId:'b',kind:'text' as const,start:index,end:index+1,text:'私が読む'[index],ruby:[],sources:[],mapping:'exact' as const,characters:1,cumulativeCharacters:index+1,pause:'none' as const};return {unitId:value.id,unitIds:[value.id],blockId:'b',start:index,end:index+1,startSeconds:start,endSeconds:end,units:[value],unitIndices:[index],timingMethod:reliable?'forced-alignment':'estimated',...(reliable?{score:.98}:{})}; }
test('PCM activity and reliable token landmarks move estimates past measured pauses without promoting low confidence',()=>{const value=runtime();const evidence=acousticTiming([0,1,2,3].map(unit),value)!;assert.equal(evidence.minimumTokenScore,.75);assert.equal(evidence.anchorCount,3);assert.ok(evidence.units[2].startSeconds>=1.6);assert.equal(unit(1).status,'low-confidence');assert.equal('score' in evidence.units[1],false);assert.ok(evidence.units.every(u=>u.endSeconds>u.startSeconds));});
test('unknown activity, too few reliable landmarks and mismatched transcripts retain text estimates',()=>{const value=runtime();delete value.speechActivity;assert.equal(acousticTiming([0,1,2,3].map(unit),value),undefined);value.speechActivity=runtime().speechActivity;value.segments.forEach(s=>{s.confidence=.1;s.status='low-confidence';});assert.equal(acousticTiming([0,1,2,3].map(unit),value),undefined);});
test('overlapping or out of range PCM activity is rejected',()=>{const value=runtime().speechActivity!;value.intervals[1].startSeconds=.7;assert.equal(validSpeechActivity(value,3),false);value.intervals[1].startSeconds=1.6;value.intervals[1].endSeconds=4;assert.equal(validSpeechActivity(value,3),false);});
test('accepted acoustic anchors remain identical; estimated display intervals use sound and retain dwell',()=>{const cues=[cue(0,0,1),cue(1,1,1.5,true),cue(2,1.5,2.25),cue(3,2.25,3)];const evidence:AcousticTimingEstimate={version:'ctc-energy-v1',minimumTokenScore:.75,anchorCount:3,units:[{unitId:'u0',blockId:'b',start:0,end:1,startSeconds:.2,endSeconds:.8},{unitId:'u2',blockId:'b',start:2,end:3,startSeconds:1.7,endSeconds:2.2},{unitId:'u3',blockId:'b',start:3,end:4,startSeconds:2.35,endSeconds:2.8}]};const result=applyAcousticTiming(cues,evidence,3);assert.strictEqual(result[1],cues[1]);assert.equal(result[0].startSeconds,.2);assert.equal(result[2].startSeconds,1.7);assert.equal(result[3].startSeconds,2.35);assert.equal(result[2].timingMethod,'acoustic-estimated');assert.equal(result[2].score,undefined);assert.equal(cues[2].startSeconds,1.5);assert.ok(result.every(c=>c.endSeconds-c.startSeconds>=.12));});
test('wrong source offsets or duplicate sound estimates are ignored, preserving every source cue',()=>{const cues=[cue(0,0,1),cue(1,1,2)];const evidence:AcousticTimingEstimate={version:'ctc-energy-v1',minimumTokenScore:.75,anchorCount:3,units:[{unitId:'u0',blockId:'b',start:1,end:2,startSeconds:.1,endSeconds:.9}]};assert.strictEqual(applyAcousticTiming(cues,evidence,2),cues);evidence.units[0].start=0;evidence.units[0].end=1;evidence.units.push({...evidence.units[0]});assert.strictEqual(applyAcousticTiming(cues,evidence,2),cues);});
