/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteImport } from './routes/books'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ApiLocalAudioFileRouteImport } from './routes/api.local-audio.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalAudioFileRoute = ApiLocalAudioFileRouteImport.update({
  id: '/api/local-audio/$file',
  path: '/api/local-audio/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/demo': typeof DemoRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/api/local-audio/$file': typeof ApiLocalAudioFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/demo': typeof DemoRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/api/local-audio/$file': typeof ApiLocalAudioFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/demo': typeof DemoRoute
  '/generate': typeof GenerateRoute
  '/library': typeof LibraryRoute
  '/api/local-audio/$file': typeof ApiLocalAudioFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/demo'
    | '/generate'
    | '/library'
    | '/api/local-audio/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/demo'
    | '/generate'
    | '/library'
    | '/api/local-audio/$file'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/demo'
    | '/generate'
    | '/library'
    | '/api/local-audio/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  DemoRoute: typeof DemoRoute
  GenerateRoute: typeof GenerateRoute
  LibraryRoute: typeof LibraryRoute
  ApiLocalAudioFileRoute: typeof ApiLocalAudioFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-audio/$file': {
      id: '/api/local-audio/$file'
      path: '/api/local-audio/$file'
      fullPath: '/api/local-audio/$file'
      preLoaderRoute: typeof ApiLocalAudioFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  DemoRoute: DemoRoute,
  GenerateRoute: GenerateRoute,
  LibraryRoute: LibraryRoute,
  ApiLocalAudioFileRoute: ApiLocalAudioFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
