/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../../deployment/public-preview.wrangler.jsonc --include-runtime=false ../../scripts/public-audio-worker-env.d.ts` (hash: 1b53d8d3ae9052cb0719a2bae2a4b20d)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./public-audio-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}