import {expect,test}from'@playwright/test';import{mkdir,writeFile}from'node:fs/promises';import{inspectWrapping}from'./wrap-inspection';import{inspectGuides}from'./guide-inspection';
import { wrappingVariants } from '../../../../scripts/ci-scope.mjs';
const fonts=['system','noto-sans-jp','noto-serif-jp','biz-udpgothic'];const manuscript='朝。\n\nABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGH。\n\n本。\n\nInternationalization。\n\n空。\n\n<ruby>超長距離観測装置<rt>ちょうちょうきょりかんそくそうち</rt></ruby>。\n\n月。\n\nABCDEFGHIJKLMNOPQRST。\n\n夕。';
// Every matrix owns its browser context and test output directory. Keep the global two-worker budget.
test.describe.configure({ mode: 'parallel' });
for(const[viewportIndex,[width,height]]of[[320,740],[390,844],[844,390]].entries()){
 const variants=wrappingVariants(process.env.RIPOLA_CI_MODE??'full',viewportIndex,fonts);
 test(`silent wrapping ${width}x${height}: fonts, sizes, ruby and real playback`,async({page},info)=>{
  info.setTimeout(180000);const folder=info.outputPath('wrapping');await mkdir(folder,{recursive:true});await page.setViewportSize({width,height});await page.goto('/');await page.getByLabel('読む文章',{exact:true}).fill(manuscript);await page.getByRole('button',{name:'テキストのみ生成して読む',exact:true}).click();await expect(page.getByTestId('current-phrase')).toBeVisible();await page.getByLabel('読む速さ（字/分）',{exact:true}).fill('3000');const results=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  for(const {family,size,ruby} of variants.silent){
   await page.getByRole('button',{name:'表示設定',exact:true}).click();await page.getByLabel('本文の書体',{exact:true}).selectOption(family);await expect(page.locator('.font-status')).toHaveText('書体の準備完了');await page.getByLabel('文字サイズ',{exact:true}).fill(String(size));await page.getByRole('switch',{name:'ルビを表示',exact:true}).setChecked(ruby);await page.getByRole('switch',{name:'句読点で間をとる',exact:true}).setChecked(false);await page.getByRole('button',{name:'閉じる',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
   await page.getByRole('button',{name:'再生',exact:true}).scrollIntoViewIfNeeded();await page.evaluate(()=>(document.activeElement as HTMLElement)?.blur());await page.keyboard.press('Home');await page.getByRole('button',{name:'再生',exact:true}).click();await expect(page.getByRole('button',{name:'一時停止',exact:true})).toBeVisible();const m=await inspectWrapping(page,1650);results.push({family,size,ruby,...m});await writeFile(`${folder}/silent-${width}.json`,JSON.stringify({width,height,results,errors},null,2)+'\n');
   expect(m.samePhraseSizeChanges).toBe(0);expect(m.frameHeightDelta).toBeLessThan(1);expect(m.stageTopDelta).toBeLessThan(1);expect(m.stageScrollDelta).toBeLessThan(1);expect(m.pageScrollDelta).toBeLessThan(1);expect(m.maxGlyphOverflow).toBeLessThan(1);expect(m.minSize).toBeGreaterThanOrEqual(24);expect(m.progressIncreases).toBeGreaterThan(10);expect(m.maximumLines).toBeGreaterThanOrEqual(2);await page.getByRole('button',{name:'一時停止',exact:true}).click();
  }expect(errors).toEqual([]);
 });
 test(`audio wrapping ${width}x${height}: fonts, ruby and media playback`,async({page},info)=>{
  info.setTimeout(180000);const folder=info.outputPath('wrapping');await mkdir(folder,{recursive:true});await page.setViewportSize({width,height});await page.goto('/');await page.getByRole('link',{name:'VOICEVOXで読む',exact:true}).click();await expect(page.getByTestId('audio-stage')).toBeVisible();await page.waitForFunction(()=>document.querySelector('audio')!.readyState>=1);const results=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  for(const {family,ruby} of variants.audio){
   await page.getByRole('button',{name:'表示設定',exact:true}).click();await page.getByLabel('本文の書体',{exact:true}).selectOption(family);await expect(page.locator('.font-status')).toHaveText('書体の準備完了');await page.getByLabel('まとめる',{exact:true}).selectOption('24');await page.getByRole('button',{name:'閉じる',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('switch',{name:'ルビを表示',exact:true}).setChecked(ruby);await page.getByRole('slider',{name:'音声の再生位置',exact:true}).fill('0');await page.waitForFunction(()=>document.querySelector('audio')!.readyState>=1&&!document.querySelector('audio')!.seeking);await page.getByRole('button',{name:'再生',exact:true}).click();await expect(page.getByRole('button',{name:'一時停止',exact:true})).toBeVisible();const m=await inspectWrapping(page,2700);results.push({family,ruby,configuredSize:42,...m});await writeFile(`${folder}/audio-${width}.json`,JSON.stringify({width,height,results,errors},null,2)+'\n');
   expect(m.samePhraseSizeChanges).toBe(0);expect(m.frameHeightDelta).toBeLessThan(1);expect(m.stageTopDelta).toBeLessThan(1);expect(m.stageScrollDelta).toBeLessThan(1);expect(m.pageScrollDelta).toBeLessThan(1);expect(m.maxGlyphOverflow).toBeLessThan(1);expect(m.minSize).toBeGreaterThanOrEqual(24);expect(m.progressIncreases).toBeGreaterThan(10);await page.getByRole('button',{name:'一時停止',exact:true}).click();const guides=await inspectGuides(page,'[data-testid="audio-stage"]');expect(guides.overlap).toBe(false);
  }expect(errors).toEqual([]);
 });
}
